baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "exampleTheme"
publishDir = "docs"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Blogs"
    pre = "pen-tool"
    url = "/blogs/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true               #For running html codes in md file